from __future__ import annotations

import argparse
import sys
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from models.original.model import OriginalPaperResNet


def shape_str(x: torch.Tensor) -> str:
    return "x".join(str(v) for v in x.shape[1:])


def param_count(module: torch.nn.Module) -> int:
    return sum(p.numel() for p in module.parameters())


def build_mermaid(model: OriginalPaperResNet, in_channels: int, height: int, width: int) -> tuple[str, dict[str, str]]:
    with torch.no_grad():
        x = torch.zeros(1, in_channels, height, width)

        x1 = model.conv1(x)
        x2 = model.conv2_x(x1)
        x3 = model.conv3_x(x2)
        x4 = model.conv4_x(x3)
        x5 = model.conv5_x(x4)
        x6 = model.conv6_x(x5)
        x7 = model.conv7_x(x6)
        x8 = model.conv8_x(x7)
        x_pool = model.pool(x8)
        x_flat = torch.flatten(x_pool, 1)
        x_out = model.head(x_flat)

    shapes = {
        "input": f"{in_channels}x{height}x{width}",
        "conv1": shape_str(x1),
        "conv2": shape_str(x2),
        "conv3": shape_str(x3),
        "conv4": shape_str(x4),
        "conv5": shape_str(x5),
        "conv6": shape_str(x6),
        "conv7": shape_str(x7),
        "conv8": shape_str(x8),
        "pool": shape_str(x_pool),
        "flat": shape_str(x_flat),
        "out": shape_str(x_out),
    }

    lines = [
        "flowchart TD",
        f'    IN["Input\\n{shapes["input"]}"]',
        f'    C1["Conv1: Conv3x3 s=1 + GroupNorm + GELU\\n{shapes["conv1"]}"]',
        f'    C2["Stage2: 2x ResBlock (32->64, second s=2)\\n{shapes["conv2"]}"]',
        f'    C3["Stage3: 2x ResBlock (64->128, second s=2)\\n{shapes["conv3"]}"]',
        f'    C4["Stage4: 2x ResBlock (128->192, second s=2)\\n{shapes["conv4"]}"]',
        f'    C5["Stage5: 2x ResBlock (192->256, second s=2)\\n{shapes["conv5"]}"]',
        f'    C6["Stage6: 2x ResBlock (256->512, second s=2)\\n{shapes["conv6"]}"]',
        f'    C7["Stage7: 2x ResBlock (512->512, second s=2)\\n{shapes["conv7"]}"]',
        f'    C8["Stage8: 2x ResBlock (512->512, s=1)\\n{shapes["conv8"]}"]',
        f'    POOL["AdaptiveAvgPool2d(1)\\n{shapes["pool"]}"]',
        f'    FLAT["Flatten\\n{shapes["flat"]}"]',
        f'    HEAD["Head: Linear 512->256 + GELU + Dropout(0.5) + Linear 256->6\\n{shapes["out"]}"]',
        "",
        "    IN --> C1 --> C2 --> C3 --> C4 --> C5 --> C6 --> C7 --> C8 --> POOL --> FLAT --> HEAD",
    ]
    return "\n".join(lines), shapes


def build_markdown(model: OriginalPaperResNet, in_channels: int, height: int, width: int) -> str:
    mermaid, shapes = build_mermaid(model, in_channels, height, width)

    total_params = param_count(model)
    trunk_params = (
        param_count(model.conv1)
        + param_count(model.conv2_x)
        + param_count(model.conv3_x)
        + param_count(model.conv4_x)
        + param_count(model.conv5_x)
        + param_count(model.conv6_x)
        + param_count(model.conv7_x)
        + param_count(model.conv8_x)
    )
    head_params = param_count(model.head)

    return "\n".join(
        [
            "# Original Paper ResNet Architecture",
            "",
            "Generated by:",
            "",
            "```bash",
            "uv run python models/original/generate_architecture_diagram.py",
            "```",
            "",
            "## Diagram",
            "",
            "```mermaid",
            mermaid,
            "```",
            "",
            "## Parameter Summary",
            "",
            "| Component | Parameters |",
            "|---|---:|",
            f"| total | {total_params:,} |",
            f"| trunk (conv1 + conv2_x..conv8_x) | {trunk_params:,} |",
            f"| head | {head_params:,} |",
            "",
            "## Output Tensor",
            "",
            "- `6` values: `[distance, height, sin(azimuth), cos(azimuth), sin(side), cos(side)]`",
            "",
            f"Default generated input shape: `{shapes['input']}`.",
        ]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Mermaid architecture diagram for OriginalPaperResNet.")
    parser.add_argument(
        "--output",
        default="models/original/ARCHITECTURE.md",
        help="Path to write markdown diagram.",
    )
    parser.add_argument("--in-channels", type=int, default=8)
    parser.add_argument("--height", type=int, default=256)
    parser.add_argument("--width", type=int, default=256)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    model = OriginalPaperResNet(in_channels=args.in_channels).eval()
    markdown = build_markdown(model, args.in_channels, args.height, args.width)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown, encoding="utf-8")
    print(f"Wrote architecture diagram to: {out_path}")


if __name__ == "__main__":
    main()
