from __future__ import annotations

import argparse
import sys
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from models.multitask_resnet_kendall_v4.model import MultiTaskResNet


def shape_str(x: torch.Tensor) -> str:
    # Skip batch dimension for readability.
    return "x".join(str(v) for v in x.shape[1:])


def param_count(module: torch.nn.Module) -> int:
    return sum(p.numel() for p in module.parameters())


def build_mermaid(model: MultiTaskResNet, in_channels: int, height: int, width: int) -> tuple[str, dict[str, str]]:
    with torch.no_grad():
        x = torch.zeros(1, in_channels, height, width)

        x_stem = model.backbone.stem(x)
        x_s1 = model.backbone.stage1(x_stem)
        x_s2 = model.backbone.stage2(x_s1)
        x_s3 = model.backbone.stage3(x_s2)
        x_s4 = model.backbone.stage4(x_s3)
        x_pool = model.backbone.pool(x_s4)
        x_flat = torch.flatten(x_pool, 1)

        out_dist = model.distance_head(x_flat)
        out_height = model.height_head(x_flat)
        out_az = model.azimuth_head(x_flat)
        out_side = model.side_head(x_flat)

    shapes = {
        "input": f"{in_channels}x{height}x{width}",
        "stem": shape_str(x_stem),
        "stage1": shape_str(x_s1),
        "stage2": shape_str(x_s2),
        "stage3": shape_str(x_s3),
        "stage4": shape_str(x_s4),
        "pool": shape_str(x_pool),
        "flat": shape_str(x_flat),
        "dist": shape_str(out_dist),
        "height": shape_str(out_height),
        "az": shape_str(out_az),
        "side": shape_str(out_side),
    }

    lines = [
        "flowchart TD",
        f'    IN["Input\\n{shapes["input"]}"]',
        f'    STEM["Stem: Conv5x5 s=1 + BN + ReLU\\n{shapes["stem"]}"]',
        f'    S1["Stage1: 2x ResidualBlock (32->32, s=1)\\n{shapes["stage1"]}"]',
        f'    S2["Stage2: 2x ResidualBlock (32->64, first s=2)\\n{shapes["stage2"]}"]',
        f'    S3["Stage3: 2x ResidualBlock (64->128, first s=2)\\n{shapes["stage3"]}"]',
        f'    S4["Stage4: 2x ResidualBlock (128->256, first s=2)\\n{shapes["stage4"]}"]',
        f'    POOL["AdaptiveAvgPool2d(1)\\n{shapes["pool"]}"]',
        f'    FLAT["Flatten\\n{shapes["flat"]}"]',
        f'    DH["Distance head: MLP 256->64->1\\n{shapes["dist"]}"]',
        f'    HH["Height head: MLP 256->64->1\\n{shapes["height"]}"]',
        f'    AH["Azimuth head: MLP 256->64->2 (sin, cos)\\n{shapes["az"]}"]',
        f'    SH["Side head: MLP 256->64->4 logits\\n{shapes["side"]}"]',
        "",
        "    IN --> STEM --> S1 --> S2 --> S3 --> S4 --> POOL --> FLAT",
        "    FLAT --> DH",
        "    FLAT --> HH",
        "    FLAT --> AH",
        "    FLAT --> SH",
    ]
    return "\n".join(lines), shapes


def build_markdown(model: MultiTaskResNet, in_channels: int, height: int, width: int) -> str:
    mermaid, shapes = build_mermaid(model, in_channels, height, width)

    total_params = param_count(model)
    backbone_params = param_count(model.backbone)
    distance_params = param_count(model.distance_head)
    height_params = param_count(model.height_head)
    azimuth_params = param_count(model.azimuth_head)
    side_params = param_count(model.side_head)

    return "\n".join(
        [
            "# MultiTask ResNet Kendall V4 Architecture",
            "",
            "Generated by:",
            "",
            "```bash",
            "uv run python models/multitask_resnet_kendall_v4/generate_architecture_diagram.py",
            "```",
            "",
            "## Diagram",
            "",
            "```mermaid",
            mermaid,
            "```",
            "",
            "## Parameter Summary",
            "",
            "| Component | Parameters |",
            "|---|---:|",
            f"| total | {total_params:,} |",
            f"| backbone | {backbone_params:,} |",
            f"| distance_head | {distance_params:,} |",
            f"| height_head | {height_params:,} |",
            f"| azimuth_head | {azimuth_params:,} |",
            f"| side_head | {side_params:,} |",
            "",
            "## Output Tensors",
            "",
            "- distance: scalar regression (meters)",
            "- height: scalar regression (meters)",
            "- azimuth_xy: 2D circular vector `[sin(theta), cos(theta)]`",
            "- side_logits: 4-class logits `[Front, Right, Back, Left]`",
            "",
            f"Default generated input shape: `{shapes['input']}`.",
        ]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate Mermaid architecture diagram for MultiTaskResNet v4.")
    parser.add_argument(
        "--output",
        default="models/multitask_resnet_kendall_v4/ARCHITECTURE.md",
        help="Path to write markdown diagram.",
    )
    parser.add_argument("--in-channels", type=int, default=24)
    parser.add_argument("--height", type=int, default=256)
    parser.add_argument("--width", type=int, default=256)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    model = MultiTaskResNet(in_channels=args.in_channels).eval()
    markdown = build_markdown(model, args.in_channels, args.height, args.width)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown, encoding="utf-8")
    print(f"Wrote architecture diagram to: {out_path}")


if __name__ == "__main__":
    main()
